// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwoWkipnXI-tdSRY8SRFzHtdVsdxsrnmQ',
    appId: '1:592045837216:web:39a29ded84c02b392172c5',
    messagingSenderId: '592045837216',
    projectId: 'greenpulsedash',
    authDomain: 'greenpulsedash.firebaseapp.com',
    storageBucket: 'greenpulsedash.firebasestorage.app',
    measurementId: 'G-M84QBGR0TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgkLHO9JonVHud49dEEjIv5Ds-WyZSCY',
    appId: '1:592045837216:android:55d37dad944333842172c5',
    messagingSenderId: '592045837216',
    projectId: 'greenpulsedash',
    storageBucket: 'greenpulsedash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ENxuFMNyASdce5e73wMvckxRIFtbwRo',
    appId: '1:592045837216:ios:9da564c37ea4165c2172c5',
    messagingSenderId: '592045837216',
    projectId: 'greenpulsedash',
    storageBucket: 'greenpulsedash.firebasestorage.app',
    iosBundleId: 'com.example.dashboardWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ENxuFMNyASdce5e73wMvckxRIFtbwRo',
    appId: '1:592045837216:ios:9da564c37ea4165c2172c5',
    messagingSenderId: '592045837216',
    projectId: 'greenpulsedash',
    storageBucket: 'greenpulsedash.firebasestorage.app',
    iosBundleId: 'com.example.dashboardWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwoWkipnXI-tdSRY8SRFzHtdVsdxsrnmQ',
    appId: '1:592045837216:web:6be69015210229482172c5',
    messagingSenderId: '592045837216',
    projectId: 'greenpulsedash',
    authDomain: 'greenpulsedash.firebaseapp.com',
    storageBucket: 'greenpulsedash.firebasestorage.app',
    measurementId: 'G-2LXT3GEP7Y',
  );
}
